{
 "title": "Service Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Service_Name",
    "query": {}
   },
   { "name": "Environment", "label": "Environment", "query": { "query": "label_values(env)" } }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_memory_usage_bytes{app=~\"$Service_Name\", env=\"$Environment\"} / 1048576 / 2979.84 * 100",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_memory_usage_bytes{app=~\"$Service_Name\", env=\"$Environment\"}/ 1048579 / 2979.84 * 100",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Available CPU Cores",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_count{app=~\"$Service_Name\", env=\"$Environment\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "increase(process_cpu_time_seconds_total{app=~\"$Service_Name\", env=\"$Environment\"}[1m])",
     "legendFormat": "{{app}}_{{process_cpu_state}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(increase(http_server_request_duration_seconds_bucket{app=~\"$Service_Name\", env=\"$Environment\"}[$__rate_interval])) by (le))",
     "legendFormat": "p 50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(increase(http_server_request_duration_seconds_bucket{app=~\"$Service_Name\", env=\"$Environment\"}[$__rate_interval])) by (le))",
     "legendFormat": "p 90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(increase(http_server_request_duration_seconds_bucket{app=~\"$Service_Name\", env=\"$Environment\"}[$__rate_interval])) by (le))",
     "legendFormat": "p 95"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(http_client_request_duration_seconds_bucket{app=~\"$Service_Name\", env=\"$Environment\"}[$__rate_interval]))",
     "legendFormat": "Throughput"
    },
    {
     "expr": "sum(increase(http_client_request_duration_seconds_bucket{app=~\"$Service_Name\", env=\"$Environment\", http_response_status_code=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(http_client_request_duration_seconds_bucket{app=~\"$Service_Name\", env=\"$Environment\", http_response_status_code!~\"2..\"}[$__rate_interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "BFF Requisicoes.Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(requisicoes_total{app=\"BFF\", env=\"$Environment\"}[$__rate_interval]))",
     "legendFormat": "Throughput"
    },
    {
     "expr": "sum(increase(requisicoes_total{app=\"BFF\", env=\"$Environment\", tipo=\"http_sucesso\"}[$__rate_interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(requisicoes_total{app=\"BFF\", env=\"$Environment\", tipo=\"http_erro_servidor\"}[$__rate_interval]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"$Service_Name\", level!=\"INFO\"} |= ``"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "service": "BFF" }
   ]
  }
 ]
}