services:
  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.96.0
    command: ["--config=/etc/otel-config.yaml"]
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
      - "8889:8889"  # Métricas (Prometheus scrapeia aqui)
    depends_on:
      - jaeger
      - loki
      - prometheus
    networks:
      - otel-net
      
  # Jaeger (Traces)
  jaeger:
    image: jaegertracing/opentelemetry-all-in-one
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      COLLECTOR_OTLP_GRPC_PORT: 4317
    ports:
      - "16686:16686"  # UI
      - "14250:14250"  # Jaeger gRPC
    networks:
      - otel-net

  # Prometheus (Métricas)
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - otel-net

  # Loki (Logs)
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - otel-net

  # Grafana (Opcional - Para visualizar tudo)
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    networks:
      - otel-net
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: emprestimos_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
  
  redis:
    image: redis
    restart: always
    command: redis-server --requirepass emprestimo!@
    ports:
      - '6379:6379'

volumes:
  grafana-storage:
  dbdata:

networks:
  otel-net:
    driver: bridge